### ISSUE TITLE
how about add a feature about auto clear the marks.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/neosnippet.vim#306]
@Shougo maybe this is not an issue,just a suggestion，some times we leave the insert mode before finish jumpping,then the marks wll not be cleared,and if we hide the marks，then the code will can not be compiled.
maybe we shoud use an autocmd autoclear the marks when the file been saved

**Comment by Shougo** [comment]
This feature is already implemented.
If it is not worked, it is bug.
But, I cannot reproduce it.
Please create the minimal .vimrc and the reproduce ways.

**Comment by wsdjeg** [comment]
ok i can reproduce it by these two snips; any filetype here i am using java as an expample
```
snippet     (
    (${1})${0}
```
```
snippet pl
options head
	System.out.println(${1});${0}
```

here is my mini vimrc
```vim
let g:python_host_prog = '/usr/bin/python'
let g:python3_host_prog = '/usr/bin/python3'

"setup & neobundle {{{
if has('vim_starting')
	if &compatible
		set nocompatible
	endif
	set runtimepath+=~/.vim/bundle/neobundle.vim/
endif
call neobundle#begin(expand('~/.vim/bundle/'))
scriptencoding utf-8
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/neosnippet.vim' "{{{
NeoBundle 'Shougo/neosnippet-snippets'
let g:neosnippet#snippets_directory='~/DotFiles/snippets'
let g:neosnippet#enable_snipmate_compatibility=1
let g:neosnippet#enable_complete_done = 1
imap <expr><TAB> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : (pumvisible() ? "\<C-n>" : "\<TAB>")
smap <expr><TAB> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
imap <expr><S-TAB> pumvisible() ? "\<C-p>" : ""
smap <expr><S-TAB> pumvisible() ? "\<C-p>" : ""
call neobundle#end()
filetype plugin indent on
syntax on
```
1. open a new java file
2. type into pl the type tab will get `System.out.println(output)<`0`>`
3. then it should be in select mode the `output` has been selected,
4. then type into `(` and type tab expand this `(` you just typed into
5. tyep type esc ,and save the file ,the neosnippet just clear the last one mark instead of all marks

 **In general，I think it is a bug of nested snips**

**Comment by Shougo** [comment]
Fixed.

**Comment by hatelove85911** [comment]
Hi, I will still face the issue sometimes:

**javascript snippet:**
```
snippet fun
options word
    function ${1}(${2}) {
        ${3}
        }${0}

```
**vimrc:**
```

let g:neosnippet#snippets_directory = g:path2VimHome . "/neosnips"
imap <C-j>     <Plug>(neosnippet_expand_or_jump)
smap <C-j>     <Plug>(neosnippet_expand_or_jump)
xmap <C-j>     <Plug>(neosnippet_expand_target)
nmap <leader>se :NeoSnippetEdit<cr>
nmap <leader>ss :NeoSnippetSource<cr>
nmap <leader>sc :NeoSnippetClearMarkers<cr>

smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
      \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

" For conceal markers.
if has('conceal')
  set conceallevel=2 concealcursor=niv
endif

```


**it can be reproduced in any snippet for any file type, here I'll use javascript file as example**
1. insert mode, type fun
2. expand the snippet
3. without any jump, escape to normal
4. move the cursor to the position of bar shown in the following code: 

```
  function () {
    |
  }|
```
5. type i to enter insert mode, 
6. type any key, you'll see something like this:
```
  function () {
    <`3`i>
  }
```
```
  function () {
    
  }<`0` >

```

**Comment by Shougo** [comment]
It is feature.
You should jump before editing.

**Comment by hatelove85911** [comment]
sorry, I'm a little confused. from the conversion above, I think the requested feature is to clear the marks if user choose to leave the insert mode early.

so my problem is after snippet expansion, **I escape to normal mode without any jump**, my understanding of the correct behavior should be all the marks will automatically cleared at that moment.

But currently it's not the case, the marks will only be cleared after buffer write.

**Comment by Shougo** [comment]
`:help g:neosnippet#enable_auto_clear_markers`

**Comment by hatelove85911** [comment]
I'm going to get the bottom of this issue.
in the help document, it says marks will be cleared when CursorMoved event happens in the buffer.
> g:neosnippet#enable_auto_clear_markers
> 		If this variable is not 0, neosnippet will clear the markers
> 		in the buffer when |BufWritePost|, |CursorMoved| and
> 		|CursorMovedI| autocmd.
> 
> 		The default value is 1.
> 
Below is the screenshot of  `au CursorMoved`:
![image](https://cloud.githubusercontent.com/assets/2359121/18371599/3dc302ae-7668-11e6-82af-051f2064319e.png)

Below is the screenshot of a file I'm editing, the `g:neosnippet#enable_auto_clear_markers` is already set to 1.
Initially the cursor is at the beginning of the parentheses after snippet expansion. Then I escaped to normal mode, and move the cursor down, those marks should have been cleared at this moment, right??? But why it's not been cleared?? 
Am I misunderstanding the document?? 
![image](https://cloud.githubusercontent.com/assets/2359121/18370673/865b6fc6-7661-11e6-9b75-abf0bebee202.png)

**Comment by Shougo** [comment]
I get it.  It is feature.

```vim
		Note: The feature does not work for multi lines snippets.
		If you want to clear them, you should use
		|:NeoSnippetClearMarkers| instead.
```

**Comment by jeromedalbert** [comment]
FYI, to have a working "auto marker clear" for multi lines snippet, I added these mappings:

```vim
inoremap <silent> <esc> <esc>:NeoSnippetClearMarkers<cr>
snoremap <silent> <esc> <esc>:NeoSnippetClearMarkers<cr>
```

This hack works for me for now. Hopefully it does not interfere with anything else.
