### ISSUE TITLE
How to have leading indentation/whitespaces

### ISSUE THREAD

**Issue by hasufell** [Shougo/neosnippet.vim#437]
I can't figure out how to create a snippet like:

```
snippet docsec
            ------------------------
            --[ ${0:DOCUMENT SECTION} ]--
            ------------------------
```

which would produce the following code

```
    ------------------------
    --[ DOCUMENT SECTION ]--
    ------------------------
```

with **always** 4 leading spaces. `options indent` doesn't do that. Adding spaces to the snippet definition is just ignored.

**Comment by Shougo** [comment]
```
If you use hard-tab for indentation inside a snippet file, neosnippet will use
'shiftwidth' instead of Vim indent plugin. This feature is useful while some
languages' indent files do not work very well (e.g.: PHP, Python).
>
	snippet if
	  if (${1:/* condition */}) {
	      ${2:// code...}
	  }
<
```

It is feature.

**Comment by hasufell** [comment]
I used hard-tab on every line and then 4 spaces, but the first line is still inserted wrong:

```
------------------------
    --[ DOCUMENT SECTION ]--
    ------------------------
```

**Comment by Shougo** [comment]
Fixed.

**Comment by hasufell** [comment]
Still doesn't work for me, I'm on commit 14d1699e3afb67785ad89671d1a1af39efb340f2 tried with both gvim and nvim-gtk

**Comment by Shougo** [comment]
Reproduced.
Please wait...

**Comment by Shougo** [comment]
Fixed.

**Comment by hasufell** [comment]
Works nicely now! :+1:
